defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *defaults
  database: dodo_development

test:
  <<: *defaults
  database: dodo_test

production:
  <<: *defaults
  database: dodo_production
